list/urls.py
from django.urls import path, re_path

from list.views import add, show, toggle_done

app_name = 'todo'

urlpatterns = [
    path('', show, name="show"),
    re_path(r'add/?', add, name="add"),
    re_path(r'toggle/(?P<item_id>[0-9]+)/?', toggle_done, name="toggle")
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('list.urls', namespace='list'))
]

list/models.py
from django.db import models

# Create your models here.
from django.db.models import CharField, BooleanField


class TodoItem(models.Model):
    description = CharField(max_length=120, default="", null=False, blank=False)
    done = BooleanField(default=False, null=False)

    def __str__(self):
        base = self.description
        if self.done:
            base = base + "[done]"
        return base

list/forms.py
from django.core.exceptions import ValidationError
from django.forms import forms, CharField


class TodoItemForm(forms.Form):
    description = CharField(max_length=120)

    def clean(self):
        try:
            if self.cleaned_data["description"].startswith(" "):
                raise ValidationError({'name': "Input cannot start with a space"}, code='invalid')
        except KeyError:
            raise ValidationError({'name': "Description must be provided"}, code='invalid')
        return self.cleaned_data

list/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse

from list.forms import TodoItemForm
from list.models import TodoItem


def show(request):
    items = TodoItem.objects.all()
    return render(request, 'list/all.html', {'items': items})

def add(request):
    form = TodoItemForm()
    if request.method == "POST":
        form = TodoItemForm(request.POST)

        if form.is_valid():
            item = TodoItem(description=form.cleaned_data["description"])
            item.save()
            return HttpResponseRedirect(reverse('list:show'))


    context = {
        'form': form
    }

    return render(request, 'list/add.html', context)

def toggle_done(request, item_id):
    item = TodoItem.objects.get(pk=item_id)
    item.done = not item.done
    item.save()
    return HttpResponseRedirect(reverse('list:show'))

list/templates/list/add.html
{% extends 'todo/base.html' %}
{% block content %}

    <div class="container">
        <form action="{% url 'list:add' %}" method="post">
            {% csrf_token %}

            {{ form.description }}

            <input type="submit">

        </form>
    </div>

{% endblock content %}

list/templates/list/all.html
{% extends 'todo/base.html' %}
{% block content %}

    <div class="container">
        <a href="{% url 'list:add' %}">New todo item</a>
        <ul>
            {% for item in items %}
                <li>
                    <a href="{% url 'list:toggle' item_id=item.id %}">
                        {% if item.done %}
                            Un-complete
                        {% else %}
                            Complete
                        {% endif %}
                    </a> {{ item.description }} {% if item.done %} [Done!] {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock content %}

list/templates/list/hello.html
{% extends 'todo/base.html' %}
{% block content %}
    {{ message }}
{% endblock content %} # python3 manage.py runserver

todo/templates/todo/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'todo/header.html' %}
<main>
    {% block content %}
    {% endblock content %}
</main>

</body>
</html>

todo/templates/todo/header.html
<header>
    <h1 class="title">Todo App :)</h1>
</header>